# Generated by Django 2.0.2 on 2019-05-11 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='jobposition',
            field=models.CharField(default='paker', max_length=200),
        ),
    ]
